const physicsQuestions = [
  {"difficulty": "easy", "question": "What is a physical quantity?", "options": ["A number without units", "A property that can be measured", "Only mass and length", "A unit of measurement"], "correct": 1},
  {"difficulty": "easy", "question": "What is the SI unit of length?", "options": ["Kilometer", "Meter", "Centimeter", "Mile"], "correct": 1},
  {"difficulty": "easy", "question": "What is the SI unit of mass?", "options": ["Gram", "Pound", "Kilogram", "Ton"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI unit of time?", "options": ["Minute", "Hour", "Second", "Day"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI unit of electric current?", "options": ["Volt", "Ampere", "Ohm", "Watt"], "correct": 1},
  {"difficulty": "easy", "question": "What is the SI unit of temperature?", "options": ["Celsius", "Fahrenheit", "Kelvin", "Rankine"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI unit of work or energy?", "options": ["Newton", "Watt", "Joule", "Pascal"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI unit of power?", "options": ["Joule", "Newton", "Watt", "Pascal"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI unit of force?", "options": ["Joule", "Newton", "Watt", "Pascal"], "correct": 1},
  {"difficulty": "easy", "question": "What is the SI unit of pressure?", "options": ["Pascal", "Joule", "Watt", "Newton"], "correct": 0},
  {"difficulty": "easy", "question": "Which prefix represents 10³?", "options": ["kilo", "milli", "micro", "nano"], "correct": 0},
  {"difficulty": "easy", "question": "Which prefix represents 10⁻³?", "options": ["micro", "milli", "nano", "kilo"], "correct": 1},
  {"difficulty": "easy", "question": "1 kilometer equals how many meters?", "options": ["10", "100", "1000", "10000"], "correct": 2},
  {"difficulty": "easy", "question": "1 hour equals how many seconds?", "options": ["60", "600", "3600", "36000"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI base unit for length?", "options": ["meter (m)", "second (s)", "candela (cd)", "ampere (A)"], "correct": 0},
  {"difficulty": "easy", "question": "What is the SI base unit for temperature?", "options": ["meter (m)", "mole (mol)", "kelvin (K)", "ampere (A)"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI base unit for temperature?", "options": ["kilogram (kg)", "ampere (A)", "kelvin (K)", "mole (mol)"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI base unit for luminous intensity?", "options": ["ampere (A)", "candela (cd)", "kilogram (kg)", "second (s)"], "correct": 1},
  {"difficulty": "easy", "question": "How many meters are in 3 kilometers?", "options": ["30", "300", "3000", "30000"], "correct": 2},
  {"difficulty": "easy", "question": "25 g is equal to how many kilograms?", "options": ["0.25", "0.025", "2.5", "25"], "correct": 1},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Watt (W)", "Pascal (Pa)", "Newton (N)", "candela (cd)"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI base unit for length?", "options": ["second (s)", "ampere (A)", "meter (m)", "candela (cd)"], "correct": 2},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Watt (W)", "Joule (J)", "Pascal (Pa)", "kilogram (kg)"], "correct": 0},
  {"difficulty": "easy", "question": "How many meters are in 15 kilometers?", "options": ["150000", "15000", "150", "1500"], "correct": 1},
  {"difficulty": "easy", "question": "What does the prefix 'milli' mean?", "options": ["10⁻⁶", "10⁻³", "10⁻⁹", "10⁹"], "correct": 1},
  {"difficulty": "easy", "question": "What is the SI base unit for mass?", "options": ["ampere (A)", "kilogram (kg)", "meter (m)", "kelvin (K)"], "correct": 1},
  {"difficulty": "easy", "question": "300 cm is equal to how many meters?", "options": ["3.0", "0.3", "30.0", "300"], "correct": 0},
  {"difficulty": "easy", "question": "What does the prefix 'giga' mean?", "options": ["10⁶", "10⁻⁹", "10⁹", "10⁻³"], "correct": 2},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Pascal (Pa)", "kelvin (K)", "Newton (N)", "Watt (W)"], "correct": 3},
  {"difficulty": "easy", "question": "What is the SI base unit for mass?", "options": ["kilogram (kg)", "kelvin (K)", "second (s)", "candela (cd)"], "correct": 0},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Watt (W)", "Newton (N)", "mole (mol)", "Pascal (Pa)"], "correct": 0},
  {"difficulty": "easy", "question": "How many meters are in 6 kilometers?", "options": ["60", "600", "6000", "60000"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI base unit for amount of substance?", "options": ["mole (mol)", "second (s)", "kilogram (kg)", "candela (cd)"], "correct": 0},
  {"difficulty": "easy", "question": "What does the prefix 'mega' mean?", "options": ["10⁶", "10⁹", "10⁻⁹", "10⁻³"], "correct": 0},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Watt (W)", "Newton (N)", "Joule (J)", "candela (cd)"], "correct": 1},
  {"difficulty": "easy", "question": "What does the prefix 'micro' mean?", "options": ["10⁻⁹", "10⁹", "10³", "10⁻⁶"], "correct": 3},
  {"difficulty": "easy", "question": "What does the prefix 'nano' mean?", "options": ["10⁶", "10⁻⁶", "10⁻³", "10⁻⁹"], "correct": 3},
  {"difficulty": "easy", "question": "How many seconds are in 8 minutes?", "options": ["480", "48", "4800", "240"], "correct": 0},
  {"difficulty": "easy", "question": "What is the SI base unit for mass?", "options": ["meter (m)", "kilogram (kg)", "ampere (A)", "second (s)"], "correct": 1},
  {"difficulty": "easy", "question": "What does the prefix 'kilo' mean?", "options": ["10⁻⁶", "10⁻⁹", "10³", "10⁶"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI base unit for temperature?", "options": ["kelvin (K)", "kilogram (kg)", "ampere (A)", "second (s)"], "correct": 0},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["kilogram (kg)", "Pascal (Pa)", "Joule (J)", "Watt (W)"], "correct": 2},
  {"difficulty": "easy", "question": "How many seconds are in 10 minutes?", "options": ["60", "600", "6000", "300"], "correct": 1},
  {"difficulty": "easy", "question": "What is the SI base unit for length?", "options": ["meter (m)", "kilogram (kg)", "kelvin (K)", "ampere (A)"], "correct": 0},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Newton (N)", "second (s)", "Watt (W)", "Joule (J)"], "correct": 3},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["meter (m)", "Newton (N)", "Joule (J)", "Pascal (Pa)"], "correct": 1},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["meter (m)", "Newton (N)", "Pascal (Pa)", "Joule (J)"], "correct": 2},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Pascal (Pa)", "ampere (A)", "Joule (J)", "Watt (W)"], "correct": 3},
  {"difficulty": "easy", "question": "10 cm is equal to how many meters?", "options": ["10", "1.0", "0.01", "0.1"], "correct": 3},
  {"difficulty": "easy", "question": "What is the SI base unit for length?", "options": ["kelvin (K)", "meter (m)", "second (s)", "mole (mol)"], "correct": 1},
  {"difficulty": "easy", "question": "What does the prefix 'kilo' mean?", "options": ["10⁻³", "10⁻⁹", "10³", "10⁶"], "correct": 2},
  {"difficulty": "easy", "question": "What does the prefix 'micro' mean?", "options": ["10⁻⁶", "10⁹", "10³", "10⁻⁹"], "correct": 0},
  {"difficulty": "easy", "question": "300 cm is equal to how many meters?", "options": ["300", "30.0", "3.0", "0.3"], "correct": 2},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Watt (W)", "Joule (J)", "Pascal (Pa)", "ampere (A)"], "correct": 1},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Newton (N)", "Pascal (Pa)", "Joule (J)", "kelvin (K)"], "correct": 0},
  {"difficulty": "easy", "question": "What is the SI base unit for mass?", "options": ["ampere (A)", "candela (cd)", "second (s)", "kilogram (kg)"], "correct": 3},
  {"difficulty": "easy", "question": "What is the SI base unit for amount of substance?", "options": ["meter (m)", "kelvin (K)", "mole (mol)", "second (s)"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI base unit for amount of substance?", "options": ["kilogram (kg)", "kelvin (K)", "mole (mol)", "second (s)"], "correct": 2},
  {"difficulty": "easy", "question": "300 cm is equal to how many meters?", "options": ["3.0", "30.0", "300", "0.3"], "correct": 0},
  {"difficulty": "easy", "question": "How many meters are in 3 kilometers?", "options": ["30", "3000", "300", "30000"], "correct": 1},
  {"difficulty": "easy", "question": "What is the SI base unit for time?", "options": ["kilogram (kg)", "ampere (A)", "candela (cd)", "second (s)"], "correct": 3},
  {"difficulty": "easy", "question": "What is the SI base unit for length?", "options": ["second (s)", "kilogram (kg)", "meter (m)", "candela (cd)"], "correct": 2},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["second (s)", "Joule (J)", "Watt (W)", "Newton (N)"], "correct": 1},
  {"difficulty": "easy", "question": "What does the prefix 'nano' mean?", "options": ["10⁹", "10³", "10⁻³", "10⁻⁹"], "correct": 3},
  {"difficulty": "easy", "question": "What does the prefix 'mega' mean?", "options": ["10⁹", "10⁶", "10³", "10⁻⁶"], "correct": 1},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["candela (cd)", "Joule (J)", "Newton (N)", "Watt (W)"], "correct": 1},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Watt (W)", "Joule (J)", "Newton (N)", "second (s)"], "correct": 1},
  {"difficulty": "easy", "question": "What is the SI base unit for amount of substance?", "options": ["mole (mol)", "ampere (A)", "kilogram (kg)", "second (s)"], "correct": 0},
  {"difficulty": "easy", "question": "How many seconds are in 15 minutes?", "options": ["90", "450", "900", "9000"], "correct": 2},
  {"difficulty": "easy", "question": "250 cm is equal to how many meters?", "options": ["25.0", "250", "2.5", "0.25"], "correct": 2},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["ampere (A)", "Watt (W)", "Joule (J)", "Pascal (Pa)"], "correct": 1},
  {"difficulty": "easy", "question": "How many meters are in 8 kilometers?", "options": ["800", "80000", "80", "8000"], "correct": 3},
  {"difficulty": "easy", "question": "How many seconds are in 3 minutes?", "options": ["180", "18", "90", "1800"], "correct": 0},
  {"difficulty": "easy", "question": "What is the SI base unit for amount of substance?", "options": ["second (s)", "candela (cd)", "kelvin (K)", "mole (mol)"], "correct": 3},
  {"difficulty": "easy", "question": "40 cm is equal to how many meters?", "options": ["0.4", "4.0", "0.04", "40"], "correct": 0},
  {"difficulty": "easy", "question": "What does the prefix 'micro' mean?", "options": ["10⁻⁶", "10⁶", "10⁹", "10⁻⁹"], "correct": 0},
  {"difficulty": "easy", "question": "What does the prefix 'milli' mean?", "options": ["10⁶", "10⁻⁹", "10⁹", "10⁻³"], "correct": 3},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Newton (N)", "Joule (J)", "Pascal (Pa)", "second (s)"], "correct": 1},
  {"difficulty": "easy", "question": "40 cm is equal to how many meters?", "options": ["40", "0.04", "0.4", "4.0"], "correct": 2},
  {"difficulty": "easy", "question": "What does the prefix 'milli' mean?", "options": ["10³", "10⁻⁹", "10⁶", "10⁻³"], "correct": 3},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["kilogram (kg)", "Newton (N)", "Pascal (Pa)", "Joule (J)"], "correct": 2},
  {"difficulty": "easy", "question": "What does the prefix 'mega' mean?", "options": ["10³", "10⁶", "10⁻⁹", "10⁻⁶"], "correct": 1},
  {"difficulty": "easy", "question": "What does the prefix 'milli' mean?", "options": ["10⁻⁹", "10⁹", "10⁶", "10⁻³"], "correct": 3},
  {"difficulty": "easy", "question": "What does the prefix 'nano' mean?", "options": ["10⁻³", "10⁻⁹", "10⁶", "10⁻⁶"], "correct": 1},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Joule (J)", "Pascal (Pa)", "Watt (W)", "meter (m)"], "correct": 0},
  {"difficulty": "easy", "question": "900 g is equal to how many kilograms?", "options": ["9.0", "90.0", "900", "0.9"], "correct": 3},
  {"difficulty": "easy", "question": "What does the prefix 'milli' mean?", "options": ["10⁶", "10³", "10⁻⁹", "10⁻³"], "correct": 3},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["candela (cd)", "Newton (N)", "Watt (W)", "Pascal (Pa)"], "correct": 3},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["second (s)", "Newton (N)", "Joule (J)", "Pascal (Pa)"], "correct": 3},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Joule (J)", "ampere (A)", "Pascal (Pa)", "Watt (W)"], "correct": 0},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["kelvin (K)", "Joule (J)", "Newton (N)", "Watt (W)"], "correct": 1},
  {"difficulty": "easy", "question": "What is the SI base unit for amount of substance?", "options": ["candela (cd)", "mole (mol)", "ampere (A)", "kilogram (kg)"], "correct": 1},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["Newton (N)", "Watt (W)", "Joule (J)", "second (s)"], "correct": 1},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["meter (m)", "Watt (W)", "Joule (J)", "Newton (N)"], "correct": 1},
  {"difficulty": "easy", "question": "What is the SI base unit for luminous intensity?", "options": ["candela (cd)", "kelvin (K)", "mole (mol)", "meter (m)"], "correct": 0},
  {"difficulty": "easy", "question": "What does the prefix 'mega' mean?", "options": ["10⁻⁶", "10⁶", "10⁻³", "10⁹"], "correct": 1},
  {"difficulty": "easy", "question": "Which of the following is a derived SI unit?", "options": ["kelvin (K)", "Newton (N)", "Watt (W)", "Joule (J)"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI base unit for temperature?", "options": ["second (s)", "meter (m)", "ampere (A)", "kelvin (K)"], "correct": 3},
  {"difficulty": "easy", "question": "What is the SI base unit for temperature?", "options": ["kilogram (kg)", "candela (cd)", "kelvin (K)", "meter (m)"], "correct": 2},
  {"difficulty": "easy", "question": "What is the SI base unit for time?", "options": ["second (s)", "kelvin (K)", "ampere (A)", "mole (mol)"], "correct": 0},
  {"difficulty": "moderate", "question": "What is the formula for power?", "options": ["P = Fd", "P = W/t", "P = mv", "P = mgh"], "correct": 1},
  {"difficulty": "moderate", "question": "Pressure is defined as", "options": ["Force × area", "Force / area", "Mass × acceleration", "Work / time"], "correct": 1},
  {"difficulty": "moderate", "question": "What does 1 Newton equal?", "options": ["1 kg·m/s²", "1 kg·m²/s²", "1 J/s", "1 N/m²"], "correct": 0},
  {"difficulty": "moderate", "question": "What does 1 Joule equal?", "options": ["1 N·m", "1 kg·m/s", "1 W·s²", "1 Pa·m"], "correct": 0},
  {"difficulty": "moderate", "question": "What does 1 Watt equal?", "options": ["1 N·m", "1 J/s", "1 N/s", "1 Pa·m³"], "correct": 1},
  {"difficulty": "moderate", "question": "What does 1 Pascal equal?", "options": ["1 N/m²", "1 J/s", "1 kg·m/s²", "1 N·m"], "correct": 0},
  {"difficulty": "moderate", "question": "What is the dimension of momentum?", "options": ["[M][L]²[T]⁻²", "[L][T]⁻¹", "[M][L]⁻¹[T]⁻²", "[M][L][T]⁻¹"], "correct": 3},
  {"difficulty": "moderate", "question": "If work is 300 J and power is 125 W, time is", "options": ["2.4 s", "3.4 s", "1.2 s", "4.8 s"], "correct": 0},
  {"difficulty": "moderate", "question": "A force of 400 N acts on an area of 8 m². Pressure is", "options": ["50.0 Pa", "25.0 Pa", "100.0 Pa", "55.0 Pa"], "correct": 0},
  {"difficulty": "moderate", "question": "If work is 600 J and power is 100 W, time is", "options": ["12.0 s", "7.0 s", "6.0 s", "3.0 s"], "correct": 2},
  {"difficulty": "moderate", "question": "A constant force of 30 N moves an object 5 m in the same direction. Work done is", "options": ["150 J", "75 J", "300 J", "180 J"], "correct": 0},
  {"difficulty": "moderate", "question": "A constant force of 8 N moves an object 12 m in the same direction. Work done is", "options": ["104 J", "48 J", "96 J", "192 J"], "correct": 2},
  {"difficulty": "moderate", "question": "If 360 J of work is done in 6 s, what is the power?", "options": ["60.0 W", "70.0 W", "120.0 W", "30.0 W"], "correct": 0},
  {"difficulty": "moderate", "question": "A force of 100 N acts on an area of 8 m². Pressure is", "options": ["17.5 Pa", "6.25 Pa", "12.5 Pa", "25.0 Pa"], "correct": 2},
  {"difficulty": "moderate", "question": "If work is 500 J and power is 125 W, time is", "options": ["4.0 s", "5.0 s", "2.0 s", "8.0 s"], "correct": 0},
  {"difficulty": "moderate", "question": "If work is 800 J and power is 125 W, time is", "options": ["12.8 s", "3.2 s", "6.4 s", "7.4 s"], "correct": 2},
  {"difficulty": "moderate", "question": "A constant force of 15 N moves an object 10 m in the same direction. Work done is", "options": ["150 J", "300 J", "165 J", "75 J"], "correct": 0},
  {"difficulty": "moderate", "question": "Which expression matches the SI base units of Watt?", "options": ["kg·m²/s²", "kg·m/s²", "kg/(m·s²)", "kg·m²/s³"], "correct": 3},
  {"difficulty": "moderate", "question": "A constant force of 15 N moves an object 3 m in the same direction. Work done is", "options": ["90 J", "45 J", "60 J", "22 J"], "correct": 1},
  {"difficulty": "moderate", "question": "If work is 600 J and power is 250 W, time is", "options": ["3.4 s", "1.2 s", "2.4 s", "4.8 s"], "correct": 2},
  {"difficulty": "moderate", "question": "If work is 500 J and power is 100 W, time is", "options": ["10.0 s", "6.0 s", "5.0 s", "2.5 s"], "correct": 2},
  {"difficulty": "moderate", "question": "A constant force of 15 N moves an object 8 m in the same direction. Work done is", "options": ["240 J", "120 J", "135 J", "60 J"], "correct": 1},
  {"difficulty": "moderate", "question": "If work is 600 J and power is 75 W, time is", "options": ["16.0 s", "9.0 s", "8.0 s", "4.0 s"], "correct": 2},
  {"difficulty": "moderate", "question": "A force of 200 N acts on an area of 10 m². Pressure is", "options": ["20.0 Pa", "25.0 Pa", "10.0 Pa", "40.0 Pa"], "correct": 0},
  {"difficulty": "moderate", "question": "What is the dimension of momentum?", "options": ["[L][T]⁻¹", "[M][L][T]⁻²", "[M][L]²[T]⁻³", "[M][L][T]⁻¹"], "correct": 3},
  {"difficulty": "moderate", "question": "A constant force of 12 N moves an object 2 m in the same direction. Work done is", "options": ["36 J", "24 J", "12 J", "48 J"], "correct": 1},
  {"difficulty": "moderate", "question": "What is the dimension of energy?", "options": ["[M][L]⁻¹[T]⁻²", "[M][L]²[T]⁻²", "[M][L]²[T]⁻³", "[L][T]⁻¹"], "correct": 1},
  {"difficulty": "moderate", "question": "What is the dimension of acceleration?", "options": ["[L][T]⁻¹", "[L][T]⁻²", "[M][L]²[T]⁻³", "[M][L]⁻¹[T]⁻²"], "correct": 1},
  {"difficulty": "moderate", "question": "Which expression matches the SI base units of Pascal?", "options": ["kg·m²/s³", "kg/(m·s²)", "kg·m/s²", "kg·m²/s²"], "correct": 1},
  {"difficulty": "moderate", "question": "If 900 J of work is done in 5 s, what is the power?", "options": ["360.0 W", "180.0 W", "190.0 W", "90.0 W"], "correct": 1},
  {"difficulty": "moderate", "question": "If 240 J of work is done in 4 s, what is the power?", "options": ["120.0 W", "30.0 W", "70.0 W", "60.0 W"], "correct": 3},
  {"difficulty": "moderate", "question": "Which expression matches the SI base units of Pascal?", "options": ["kg·m/s²", "kg·m²/s²", "kg/(m·s²)", "kg·m²/s³"], "correct": 2},
  {"difficulty": "moderate", "question": "If work is 400 J and power is 200 W, time is", "options": ["4.0 s", "1.0 s", "2.0 s", "3.0 s"], "correct": 2},
  {"difficulty": "moderate", "question": "A constant force of 15 N moves an object 10 m in the same direction. Work done is", "options": ["75 J", "165 J", "300 J", "150 J"], "correct": 3},
  {"difficulty": "moderate", "question": "If work is 300 J and power is 100 W, time is", "options": ["4.0 s", "1.5 s", "3.0 s", "6.0 s"], "correct": 2},
  {"difficulty": "moderate", "question": "If 300 J of work is done in 18 s, what is the power?", "options": ["26.67 W", "16.67 W", "33.34 W", "8.34 W"], "correct": 1},
  {"difficulty": "moderate", "question": "Which expression matches the SI base units of Watt?", "options": ["kg·m/s²", "kg/(m·s²)", "kg·m²/s²", "kg·m²/s³"], "correct": 3},
  {"difficulty": "moderate", "question": "A force of 100 N acts on an area of 5 m². Pressure is", "options": ["20.0 Pa", "40.0 Pa", "25.0 Pa", "10.0 Pa"], "correct": 0},
  {"difficulty": "moderate", "question": "What is the dimension of velocity?", "options": ["[M][L]⁻¹[T]⁻²", "[M][L][T]⁻²", "[L][T]⁻¹", "[L][T]⁻²"], "correct": 2},
  {"difficulty": "moderate", "question": "If 500 J of work is done in 15 s, what is the power?", "options": ["16.66 W", "33.33 W", "66.66 W", "43.33 W"], "correct": 1},
  {"difficulty": "moderate", "question": "A force of 250 N acts on an area of 10 m². Pressure is", "options": ["12.5 Pa", "50.0 Pa", "25.0 Pa", "30.0 Pa"], "correct": 2},
  {"difficulty": "moderate", "question": "A constant force of 25 N moves an object 8 m in the same direction. Work done is", "options": ["100 J", "200 J", "225 J", "400 J"], "correct": 1},
  {"difficulty": "moderate", "question": "If 360 J of work is done in 10 s, what is the power?", "options": ["36.0 W", "18.0 W", "72.0 W", "46.0 W"], "correct": 0},
  {"difficulty": "moderate", "question": "A force of 100 N acts on an area of 5 m². Pressure is", "options": ["25.0 Pa", "10.0 Pa", "40.0 Pa", "20.0 Pa"], "correct": 3},
  {"difficulty": "moderate", "question": "A constant force of 10 N moves an object 10 m in the same direction. Work done is", "options": ["110 J", "50 J", "200 J", "100 J"], "correct": 3},
  {"difficulty": "moderate", "question": "Which expression matches the SI base units of Newton?", "options": ["kg·m²/s³", "kg/(m·s²)", "kg·m²/s²", "kg·m/s²"], "correct": 3},
  {"difficulty": "moderate", "question": "A constant force of 35 N moves an object 4 m in the same direction. Work done is", "options": ["140 J", "175 J", "70 J", "280 J"], "correct": 0},
  {"difficulty": "moderate", "question": "What is the dimension of velocity?", "options": ["[M][L][T]⁻²", "[M][L][T]⁻¹", "[L][T]⁻¹", "[M][L]⁻¹[T]⁻²"], "correct": 2},
  {"difficulty": "moderate", "question": "A force of 250 N acts on an area of 2 m². Pressure is", "options": ["62.5 Pa", "130.0 Pa", "125.0 Pa", "250.0 Pa"], "correct": 2},
  {"difficulty": "moderate", "question": "What is the dimension of pressure?", "options": ["[L][T]⁻²", "[M][L]⁻¹[T]⁻²", "[M][L]²[T]⁻²", "[M][L][T]⁻²"], "correct": 1},
  {"difficulty": "moderate", "question": "Which expression matches the SI base units of Joule?", "options": ["kg·m²/s²", "kg·m²/s³", "kg/(m·s²)", "kg·m/s²"], "correct": 0},
  {"difficulty": "moderate", "question": "What is the dimension of force?", "options": ["[M][L][T]⁻²", "[M][L]⁻¹[T]⁻²", "[M][L]²[T]⁻²", "[M][L]²[T]⁻³"], "correct": 0},
  {"difficulty": "moderate", "question": "A force of 300 N acts on an area of 10 m². Pressure is", "options": ["15.0 Pa", "60.0 Pa", "30.0 Pa", "35.0 Pa"], "correct": 2},
  {"difficulty": "moderate", "question": "A force of 250 N acts on an area of 4 m². Pressure is", "options": ["62.5 Pa", "125.0 Pa", "67.5 Pa", "31.25 Pa"], "correct": 0},
  {"difficulty": "moderate", "question": "Which expression matches the SI base units of Watt?", "options": ["kg·m²/s²", "kg·m/s²", "kg·m²/s³", "kg/(m·s²)"], "correct": 2},
  {"difficulty": "moderate", "question": "A constant force of 30 N moves an object 10 m in the same direction. Work done is", "options": ["150 J", "300 J", "600 J", "330 J"], "correct": 1},
  {"difficulty": "moderate", "question": "Which expression matches the SI base units of Newton?", "options": ["kg/(m·s²)", "kg·m²/s³", "kg·m²/s²", "kg·m/s²"], "correct": 3},
  {"difficulty": "moderate", "question": "What is the dimension of pressure?", "options": ["[M][L]⁻¹[T]⁻²", "[M][L][T]⁻¹", "[M][L]²[T]⁻²", "[L][T]⁻²"], "correct": 0},
  {"difficulty": "moderate", "question": "A constant force of 25 N moves an object 3 m in the same direction. Work done is", "options": ["75 J", "37 J", "100 J", "150 J"], "correct": 0},
  {"difficulty": "moderate", "question": "A constant force of 30 N moves an object 2 m in the same direction. Work done is", "options": ["120 J", "30 J", "90 J", "60 J"], "correct": 3},
  {"difficulty": "moderate", "question": "If 150 J of work is done in 10 s, what is the power?", "options": ["30.0 W", "25.0 W", "7.5 W", "15.0 W"], "correct": 3},
  {"difficulty": "moderate", "question": "Which expression matches the SI base units of Joule?", "options": ["kg·m/s²", "kg·m²/s²", "kg·m²/s³", "kg/(m·s²)"], "correct": 1},
  {"difficulty": "moderate", "question": "A constant force of 20 N moves an object 8 m in the same direction. Work done is", "options": ["80 J", "320 J", "160 J", "180 J"], "correct": 2},
  {"difficulty": "moderate", "question": "A force of 250 N acts on an area of 8 m². Pressure is", "options": ["36.25 Pa", "15.62 Pa", "31.25 Pa", "62.5 Pa"], "correct": 2},
  {"difficulty": "moderate", "question": "What is the dimension of power?", "options": ["[M][L]⁻¹[T]⁻²", "[M][L]²[T]⁻²", "[L][T]⁻²", "[M][L]²[T]⁻³"], "correct": 3},
  {"difficulty": "moderate", "question": "If 500 J of work is done in 6 s, what is the power?", "options": ["41.66 W", "83.33 W", "166.66 W", "93.33 W"], "correct": 1},
  {"difficulty": "moderate", "question": "Which expression matches the SI base units of Watt?", "options": ["kg/(m·s²)", "kg·m²/s²", "kg·m/s²", "kg·m²/s³"], "correct": 3},
  {"difficulty": "moderate", "question": "If work is 500 J and power is 200 W, time is", "options": ["2.5 s", "3.5 s", "5.0 s", "1.25 s"], "correct": 0},
  {"difficulty": "moderate", "question": "If 450 J of work is done in 12 s, what is the power?", "options": ["18.75 W", "75.0 W", "47.5 W", "37.5 W"], "correct": 3},
  {"difficulty": "moderate", "question": "A force of 200 N acts on an area of 8 m². Pressure is", "options": ["25.0 Pa", "50.0 Pa", "30.0 Pa", "12.5 Pa"], "correct": 0},
  {"difficulty": "moderate", "question": "What is the dimension of momentum?", "options": ["[M][L]²[T]⁻²", "[M][L][T]⁻¹", "[M][L][T]⁻²", "[M][L]⁻¹[T]⁻²"], "correct": 1},
  {"difficulty": "moderate", "question": "A force of 350 N acts on an area of 5 m². Pressure is", "options": ["75.0 Pa", "140.0 Pa", "70.0 Pa", "35.0 Pa"], "correct": 2},
  {"difficulty": "moderate", "question": "If 900 J of work is done in 5 s, what is the power?", "options": ["360.0 W", "180.0 W", "190.0 W", "90.0 W"], "correct": 1},
  {"difficulty": "moderate", "question": "If work is 200 J and power is 200 W, time is", "options": ["2.0 s", "0.5 s", "2.0 s", "1.0 s"], "correct": 3},
  {"difficulty": "moderate", "question": "What is the dimension of power?", "options": ["[M][L][T]⁻²", "[M][L]²[T]⁻³", "[L][T]⁻²", "[L][T]⁻¹"], "correct": 1},
  {"difficulty": "moderate", "question": "If 240 J of work is done in 4 s, what is the power?", "options": ["60.0 W", "120.0 W", "70.0 W", "30.0 W"], "correct": 0},
  {"difficulty": "moderate", "question": "If 300 J of work is done in 12 s, what is the power?", "options": ["25.0 W", "50.0 W", "35.0 W", "12.5 W"], "correct": 0},
  {"difficulty": "moderate", "question": "What is the dimension of energy?", "options": ["[L][T]⁻¹", "[L][T]⁻²", "[M][L]⁻¹[T]⁻²", "[M][L]²[T]⁻²"], "correct": 3},
  {"difficulty": "moderate", "question": "What is the dimension of momentum?", "options": ["[M][L][T]⁻¹", "[M][L][T]⁻²", "[L][T]⁻¹", "[M][L]²[T]⁻²"], "correct": 0},
  {"difficulty": "moderate", "question": "If work is 800 J and power is 200 W, time is", "options": ["4.0 s", "8.0 s", "5.0 s", "2.0 s"], "correct": 0},
  {"difficulty": "moderate", "question": "If work is 400 J and power is 50 W, time is", "options": ["4.0 s", "8.0 s", "9.0 s", "16.0 s"], "correct": 1},
  {"difficulty": "moderate", "question": "A force of 300 N acts on an area of 4 m². Pressure is", "options": ["80.0 Pa", "75.0 Pa", "37.5 Pa", "150.0 Pa"], "correct": 1},
  {"difficulty": "moderate", "question": "If work is 1000 J and power is 125 W, time is", "options": ["8.0 s", "16.0 s", "9.0 s", "4.0 s"], "correct": 0},
  {"difficulty": "moderate", "question": "What is the dimension of acceleration?", "options": ["[M][L][T]⁻¹", "[M][L]²[T]⁻²", "[L][T]⁻¹", "[L][T]⁻²"], "correct": 3},
  {"difficulty": "moderate", "question": "If 600 J of work is done in 4 s, what is the power?", "options": ["150.0 W", "75.0 W", "300.0 W", "160.0 W"], "correct": 0},
  {"difficulty": "moderate", "question": "If work is 800 J and power is 200 W, time is", "options": ["8.0 s", "4.0 s", "2.0 s", "5.0 s"], "correct": 1},
  {"difficulty": "moderate", "question": "Which expression matches the SI base units of Newton?", "options": ["kg·m/s²", "kg/(m·s²)", "kg·m²/s²", "kg·m²/s³"], "correct": 0},
  {"difficulty": "moderate", "question": "If 500 J of work is done in 12 s, what is the power?", "options": ["20.84 W", "41.67 W", "51.67 W", "83.34 W"], "correct": 1},
  {"difficulty": "moderate", "question": "If work is 400 J and power is 150 W, time is", "options": ["3.67 s", "5.34 s", "2.67 s", "1.33 s"], "correct": 2},
  {"difficulty": "moderate", "question": "A constant force of 15 N moves an object 3 m in the same direction. Work done is", "options": ["22 J", "90 J", "45 J", "60 J"], "correct": 2},
  {"difficulty": "moderate", "question": "If work is 800 J and power is 150 W, time is", "options": ["2.67 s", "10.66 s", "6.33 s", "5.33 s"], "correct": 3},
  {"difficulty": "moderate", "question": "If 200 J of work is done in 18 s, what is the power?", "options": ["21.11 W", "5.55 W", "11.11 W", "22.22 W"], "correct": 2},
  {"difficulty": "moderate", "question": "A force of 150 N acts on an area of 3 m². Pressure is", "options": ["100.0 Pa", "55.0 Pa", "50.0 Pa", "25.0 Pa"], "correct": 2},
  {"difficulty": "moderate", "question": "A constant force of 12 N moves an object 4 m in the same direction. Work done is", "options": ["24 J", "60 J", "48 J", "96 J"], "correct": 2},
  {"difficulty": "moderate", "question": "If work is 1000 J and power is 50 W, time is", "options": ["10.0 s", "21.0 s", "20.0 s", "40.0 s"], "correct": 2},
  {"difficulty": "moderate", "question": "If 750 J of work is done in 8 s, what is the power?", "options": ["46.88 W", "187.5 W", "103.75 W", "93.75 W"], "correct": 3},
  {"difficulty": "moderate", "question": "What is the dimension of acceleration?", "options": ["[L][T]⁻²", "[L][T]⁻¹", "[M][L]²[T]⁻³", "[M][L][T]⁻¹"], "correct": 0},
  {"difficulty": "moderate", "question": "A constant force of 35 N moves an object 3 m in the same direction. Work done is", "options": ["52 J", "105 J", "210 J", "140 J"], "correct": 1},
  {"difficulty": "moderate", "question": "A force of 100 N acts on an area of 10 m². Pressure is", "options": ["15.0 Pa", "10.0 Pa", "20.0 Pa", "5.0 Pa"], "correct": 1},
  {"difficulty": "moderate", "question": "What is the dimension of energy?", "options": ["[M][L]²[T]⁻³", "[M][L][T]⁻¹", "[L][T]⁻¹", "[M][L]²[T]⁻²"], "correct": 3},
  {"difficulty": "extreme", "question": "A 2 kg object is lifted 11 m. Use g = 9.8 m/s². Gain in potential energy is", "options": ["235.2 J", "107.8 J", "215.6 J", "431.2 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 10 kg object speeds up from 10 m/s to 21 m/s. Change in kinetic energy is", "options": ["1705.0 J", "1720.0 J", "3410.0 J", "852.5 J"], "correct": 0},
  {"difficulty": "extreme", "question": "Which expression is dimensionally correct for energy?", "options": ["MLT⁻²", "ML²T⁻²", "MLT⁻¹", "LT⁻²"], "correct": 1},
  {"difficulty": "extreme", "question": "A machine outputs 60 J of useful work for every 100 J input. Efficiency is", "options": ["40%", "55%", "65%", "60%"], "correct": 3},
  {"difficulty": "extreme", "question": "A machine outputs 80 J of useful work for every 100 J input. Efficiency is", "options": ["80%", "85%", "75%", "20%"], "correct": 0},
  {"difficulty": "extreme", "question": "Power has SI base units of", "options": ["kg·m/s²", "kg·m²/s²", "kg·m²/s³", "kg/(m·s²)"], "correct": 2},
  {"difficulty": "extreme", "question": "A machine outputs 90 J of useful work for every 100 J input. Efficiency is", "options": ["85%", "95%", "10%", "90%"], "correct": 3},
  {"difficulty": "extreme", "question": "A 750 W device runs for 6 minutes. Energy used is", "options": ["270000 J", "270750 J", "540000 J", "135000 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 2 kg object is lifted 27 m. Use g = 9.8 m/s². Gain in potential energy is", "options": ["264.6 J", "1058.4 J", "548.8 J", "529.2 J"], "correct": 3},
  {"difficulty": "extreme", "question": "A 12 kg object is lifted 24 m. Use g = 9.8 m/s². Gain in potential energy is", "options": ["5644.8 J", "2842.0 J", "2822.4 J", "1411.2 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 300 W device runs for 8 minutes. Energy used is", "options": ["144000 J", "72000 J", "144300 J", "288000 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 5 kg object moves at 11 m/s. What is its kinetic energy?", "options": ["312.5 J", "302.5 J", "605.0 J", "151.2 J"], "correct": 1},
  {"difficulty": "extreme", "question": "A device does 783 J of work in 23 s. Power output is closest to", "options": ["68.0 W", "17.0 W", "34.0 W", "59.0 W"], "correct": 2},
  {"difficulty": "extreme", "question": "A 1000 W device runs for 2 minutes. Energy used is", "options": ["60000 J", "120000 J", "121000 J", "240000 J"], "correct": 1},
  {"difficulty": "extreme", "question": "A machine outputs 85 J of useful work for every 100 J input. Efficiency is", "options": ["80%", "15%", "90%", "85%"], "correct": 3},
  {"difficulty": "extreme", "question": "A 3 kg object moves at 6 m/s. What is its kinetic energy?", "options": ["54.0 J", "64.0 J", "108.0 J", "27.0 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 3 kg object moves at 15 m/s. What is its kinetic energy?", "options": ["337.5 J", "347.5 J", "168.8 J", "675.0 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 3 kg object is lifted 24 m. Use g = 9.8 m/s². Gain in potential energy is", "options": ["1411.2 J", "352.8 J", "725.2 J", "705.6 J"], "correct": 3},
  {"difficulty": "extreme", "question": "A machine outputs 80 J of useful work for every 100 J input. Efficiency is", "options": ["85%", "80%", "20%", "75%"], "correct": 1},
  {"difficulty": "extreme", "question": "A 750 W device runs for 6 minutes. Energy used is", "options": ["135000 J", "540000 J", "270750 J", "270000 J"], "correct": 3},
  {"difficulty": "extreme", "question": "A 8 N force acts at 0° to displacement 12 m. Work done is closest to", "options": ["96.0 J", "106.0 J", "96 J", "0.0 J"], "correct": 0},
  {"difficulty": "extreme", "question": "Which expression is dimensionally correct for energy?", "options": ["MLT⁻²", "ML²T⁻²", "MLT⁻¹", "LT⁻²"], "correct": 1},
  {"difficulty": "extreme", "question": "Power has SI base units of", "options": ["kg·m/s²", "kg·m²/s²", "kg·m²/s³", "kg/(m·s²)"], "correct": 2},
  {"difficulty": "extreme", "question": "A 4 kg object speeds up from 8 m/s to 11 m/s. Change in kinetic energy is", "options": ["129.0 J", "114.0 J", "228.0 J", "57.0 J"], "correct": 1},
  {"difficulty": "extreme", "question": "A 10 kg object speeds up from 7 m/s to 17 m/s. Change in kinetic energy is", "options": ["2400.0 J", "1215.0 J", "1200.0 J", "600.0 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A machine outputs 85 J of useful work for every 100 J input. Efficiency is", "options": ["15%", "90%", "80%", "85%"], "correct": 3},
  {"difficulty": "extreme", "question": "A 4 kg object speeds up from 2 m/s to 8 m/s. Change in kinetic energy is", "options": ["135.0 J", "120.0 J", "240.0 J", "60.0 J"], "correct": 1},
  {"difficulty": "extreme", "question": "A 8 kg object moves at 13 m/s. What is its kinetic energy?", "options": ["1352.0 J", "338.0 J", "676.0 J", "686.0 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A machine outputs 85 J of useful work for every 100 J input. Efficiency is", "options": ["85%", "80%", "90%", "15%"], "correct": 0},
  {"difficulty": "extreme", "question": "A 7 kg object is lifted 28 m. Use g = 9.8 m/s². Gain in potential energy is", "options": ["960.4 J", "1940.4 J", "3841.6 J", "1920.8 J"], "correct": 3},
  {"difficulty": "extreme", "question": "If speed doubles, kinetic energy becomes", "options": ["Double", "Half", "Four times", "Same"], "correct": 2},
  {"difficulty": "extreme", "question": "A 1200 W device runs for 8 minutes. Energy used is", "options": ["1152000 J", "576000 J", "288000 J", "577200 J"], "correct": 1},
  {"difficulty": "extreme", "question": "A machine outputs 60 J of useful work for every 100 J input. Efficiency is", "options": ["55%", "40%", "60%", "65%"], "correct": 2},
  {"difficulty": "extreme", "question": "A 300 W device runs for 8 minutes. Energy used is", "options": ["288000 J", "72000 J", "144300 J", "144000 J"], "correct": 3},
  {"difficulty": "extreme", "question": "A machine outputs 85 J of useful work for every 100 J input. Efficiency is", "options": ["80%", "90%", "15%", "85%"], "correct": 3},
  {"difficulty": "extreme", "question": "A 500 W device runs for 6 minutes. Energy used is", "options": ["180500 J", "360000 J", "180000 J", "90000 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A device does 1581 J of work in 13 s. Power output is closest to", "options": ["146.6 W", "60.8 W", "121.6 W", "243.2 W"], "correct": 2},
  {"difficulty": "extreme", "question": "A 21 N force acts at 30° to displacement 5 m. Work done is closest to", "options": ["100.9 J", "90.9 J", "52.5 J", "105 J"], "correct": 1},
  {"difficulty": "extreme", "question": "A 36 N force acts at 60° to displacement 9 m. Work done is closest to", "options": ["162.0 J", "324 J", "172.0 J", "280.6 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 33 N force acts at 60° to displacement 3 m. Work done is closest to", "options": ["49.5 J", "99 J", "85.7 J", "59.5 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 10 kg object speeds up from 0 m/s to 7 m/s. Change in kinetic energy is", "options": ["260.0 J", "122.5 J", "490.0 J", "245.0 J"], "correct": 3},
  {"difficulty": "extreme", "question": "If speed doubles, kinetic energy becomes", "options": ["Double", "Half", "Four times", "Same"], "correct": 2},
  {"difficulty": "extreme", "question": "A 6 kg object moves at 15 m/s. What is its kinetic energy?", "options": ["1350.0 J", "685.0 J", "675.0 J", "337.5 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A machine outputs 80 J of useful work for every 100 J input. Efficiency is", "options": ["85%", "75%", "20%", "80%"], "correct": 3},
  {"difficulty": "extreme", "question": "A 1500 W device runs for 12 minutes. Energy used is", "options": ["2160000 J", "1081500 J", "1080000 J", "540000 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 6 kg object is lifted 23 m. Use g = 9.8 m/s². Gain in potential energy is", "options": ["2704.8 J", "1372.0 J", "676.2 J", "1352.4 J"], "correct": 3},
  {"difficulty": "extreme", "question": "A 4 kg object moves at 13 m/s. What is its kinetic energy?", "options": ["169.0 J", "338.0 J", "676.0 J", "348.0 J"], "correct": 1},
  {"difficulty": "extreme", "question": "A 1000 W device runs for 5 minutes. Energy used is", "options": ["300000 J", "600000 J", "150000 J", "301000 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 11 kg object moves at 12 m/s. What is its kinetic energy?", "options": ["802.0 J", "1584.0 J", "792.0 J", "396.0 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 9 kg object is lifted 22 m. Use g = 9.8 m/s². Gain in potential energy is", "options": ["1940.4 J", "970.2 J", "3880.8 J", "1960.0 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 26 N force acts at 30° to displacement 3 m. Work done is closest to", "options": ["67.5 J", "77.5 J", "78 J", "39.0 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 10 N force acts at 60° to displacement 6 m. Work done is closest to", "options": ["60 J", "40.0 J", "30.0 J", "52.0 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A machine outputs 85 J of useful work for every 100 J input. Efficiency is", "options": ["80%", "15%", "85%", "90%"], "correct": 2},
  {"difficulty": "extreme", "question": "A 3 kg object speeds up from 3 m/s to 10 m/s. Change in kinetic energy is", "options": ["273.0 J", "68.2 J", "136.5 J", "151.5 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 14 N force acts at 45° to displacement 3 m. Work done is closest to", "options": ["42 J", "39.7 J", "29.7 J", "29.7 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 400 W device runs for 8 minutes. Energy used is", "options": ["192400 J", "384000 J", "192000 J", "96000 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 33 N force acts at 60° to displacement 2 m. Work done is closest to", "options": ["66 J", "33.0 J", "43.0 J", "57.2 J"], "correct": 1},
  {"difficulty": "extreme", "question": "Which expression is dimensionally correct for energy?", "options": ["MLT⁻²", "ML²T⁻²", "MLT⁻¹", "LT⁻²"], "correct": 1},
  {"difficulty": "extreme", "question": "A 8 kg object speeds up from 3 m/s to 13 m/s. Change in kinetic energy is", "options": ["640.0 J", "320.0 J", "655.0 J", "1280.0 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A device does 1656 J of work in 23 s. Power output is closest to", "options": ["72.0 W", "36.0 W", "144.0 W", "97.0 W"], "correct": 0},
  {"difficulty": "extreme", "question": "A machine outputs 85 J of useful work for every 100 J input. Efficiency is", "options": ["15%", "90%", "85%", "80%"], "correct": 2},
  {"difficulty": "extreme", "question": "A 21 N force acts at 60° to displacement 2 m. Work done is closest to", "options": ["42 J", "21.0 J", "31.0 J", "36.4 J"], "correct": 1},
  {"difficulty": "extreme", "question": "A 5 kg object is lifted 3 m. Use g = 9.8 m/s². Gain in potential energy is", "options": ["147.0 J", "73.5 J", "166.6 J", "294.0 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 32 N force acts at 30° to displacement 3 m. Work done is closest to", "options": ["48.0 J", "83.1 J", "96 J", "93.1 J"], "correct": 1},
  {"difficulty": "extreme", "question": "A machine outputs 60 J of useful work for every 100 J input. Efficiency is", "options": ["60%", "40%", "65%", "55%"], "correct": 0},
  {"difficulty": "extreme", "question": "A device does 1731 J of work in 4 s. Power output is closest to", "options": ["865.6 W", "457.8 W", "432.8 W", "216.4 W"], "correct": 2},
  {"difficulty": "extreme", "question": "A 300 W device runs for 6 minutes. Energy used is", "options": ["108300 J", "216000 J", "108000 J", "54000 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 8 kg object speeds up from 2 m/s to 11 m/s. Change in kinetic energy is", "options": ["936.0 J", "468.0 J", "234.0 J", "483.0 J"], "correct": 1},
  {"difficulty": "extreme", "question": "A 1 kg object is lifted 9 m. Use g = 9.8 m/s². Gain in potential energy is", "options": ["44.1 J", "107.8 J", "88.2 J", "176.4 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 5 kg object is lifted 8 m. Use g = 9.8 m/s². Gain in potential energy is", "options": ["784.0 J", "411.6 J", "392.0 J", "196.0 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A device does 1869 J of work in 22 s. Power output is closest to", "options": ["170.0 W", "42.5 W", "85.0 W", "110.0 W"], "correct": 2},
  {"difficulty": "extreme", "question": "Which expression is dimensionally correct for energy?", "options": ["MLT⁻²", "ML²T⁻²", "MLT⁻¹", "LT⁻²"], "correct": 1},
  {"difficulty": "extreme", "question": "A 11 kg object moves at 10 m/s. What is its kinetic energy?", "options": ["560.0 J", "550.0 J", "275.0 J", "1100.0 J"], "correct": 1},
  {"difficulty": "extreme", "question": "A 7 kg object speeds up from 0 m/s to 11 m/s. Change in kinetic energy is", "options": ["438.5 J", "847.0 J", "423.5 J", "211.8 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 10 N force acts at 45° to displacement 10 m. Work done is closest to", "options": ["100 J", "80.7 J", "70.7 J", "70.7 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A machine outputs 80 J of useful work for every 100 J input. Efficiency is", "options": ["75%", "20%", "85%", "80%"], "correct": 3},
  {"difficulty": "extreme", "question": "A 750 W device runs for 1 minutes. Energy used is", "options": ["45750 J", "22500 J", "45000 J", "90000 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A device does 574 J of work in 20 s. Power output is closest to", "options": ["57.4 W", "53.7 W", "28.7 W", "14.3 W"], "correct": 2},
  {"difficulty": "extreme", "question": "A 1000 W device runs for 3 minutes. Energy used is", "options": ["180000 J", "90000 J", "360000 J", "181000 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 13 N force acts at 60° to displacement 3 m. Work done is closest to", "options": ["33.8 J", "29.5 J", "39 J", "19.5 J"], "correct": 3},
  {"difficulty": "extreme", "question": "A 4 kg object moves at 16 m/s. What is its kinetic energy?", "options": ["522.0 J", "256.0 J", "1024.0 J", "512.0 J"], "correct": 3},
  {"difficulty": "extreme", "question": "A machine outputs 85 J of useful work for every 100 J input. Efficiency is", "options": ["90%", "85%", "15%", "80%"], "correct": 1},
  {"difficulty": "extreme", "question": "A device does 1321 J of work in 13 s. Power output is closest to", "options": ["126.6 W", "203.2 W", "50.8 W", "101.6 W"], "correct": 3},
  {"difficulty": "extreme", "question": "A 2 kg object speeds up from 5 m/s to 13 m/s. Change in kinetic energy is", "options": ["144.0 J", "288.0 J", "72.0 J", "159.0 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A machine outputs 75 J of useful work for every 100 J input. Efficiency is", "options": ["75%", "80%", "70%", "25%"], "correct": 0},
  {"difficulty": "extreme", "question": "A 750 W device runs for 2 minutes. Energy used is", "options": ["180000 J", "45000 J", "90000 J", "90750 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 39 N force acts at 45° to displacement 6 m. Work done is closest to", "options": ["165.5 J", "234 J", "175.5 J", "165.5 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 5 kg object speeds up from 7 m/s to 18 m/s. Change in kinetic energy is", "options": ["343.8 J", "1375.0 J", "687.5 J", "702.5 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 1500 W device runs for 1 minutes. Energy used is", "options": ["90000 J", "45000 J", "91500 J", "180000 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 1 kg object speeds up from 1 m/s to 13 m/s. Change in kinetic energy is", "options": ["42.0 J", "84.0 J", "168.0 J", "99.0 J"], "correct": 1},
  {"difficulty": "extreme", "question": "A 3 kg object moves at 15 m/s. What is its kinetic energy?", "options": ["675.0 J", "168.8 J", "337.5 J", "347.5 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 4 kg object is lifted 25 m. Use g = 9.8 m/s². Gain in potential energy is", "options": ["980.0 J", "999.6 J", "1960.0 J", "490.0 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A 10 kg object moves at 4 m/s. What is its kinetic energy?", "options": ["80.0 J", "40.0 J", "160.0 J", "90.0 J"], "correct": 0},
  {"difficulty": "extreme", "question": "If speed doubles, kinetic energy becomes", "options": ["Double", "Half", "Four times", "Same"], "correct": 2},
  {"difficulty": "extreme", "question": "A 38 N force acts at 60° to displacement 7 m. Work done is closest to", "options": ["133.0 J", "266 J", "143.0 J", "230.4 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A device does 614 J of work in 2 s. Power output is closest to", "options": ["307.0 W", "153.5 W", "332.0 W", "614.0 W"], "correct": 0},
  {"difficulty": "extreme", "question": "A 5 kg object is lifted 25 m. Use g = 9.8 m/s². Gain in potential energy is", "options": ["1225.0 J", "2450.0 J", "1244.6 J", "612.5 J"], "correct": 0},
  {"difficulty": "extreme", "question": "A device does 1319 J of work in 24 s. Power output is closest to", "options": ["110.0 W", "27.5 W", "55.0 W", "80.0 W"], "correct": 2},
  {"difficulty": "extreme", "question": "A 9 N force acts at 30° to displacement 9 m. Work done is closest to", "options": ["40.5 J", "81 J", "70.1 J", "80.1 J"], "correct": 2},
  {"difficulty": "extreme", "question": "A 300 W device runs for 12 minutes. Energy used is", "options": ["216300 J", "216000 J", "108000 J", "432000 J"], "correct": 1}
];
